### ISSUE TITLE
Adding a "export sessions to file" function

### ISSUE THREAD

**Issue by Mayeu** [tslocum/MeditationAssistant#3]
Hello,

I just discovered this application on F-Droid, and the fact that it remember the sessions done is what is missing for most other FOSS application!

Since I don't want to share my data online, I'm wondering if you are planning to add the possibility to export the sessions to a simple file instead of only online?

regards,

**Comment by tslocum** [comment]
This is indeed present in the TODO file.  I don't have an ETA, but would expect to implement it within the next few releases.

**Comment by Mayeu** [comment]
Ha... did not saw the TODO file! Sorry for the noise :)
Great to know that you planned this feature :+1: I'll be sure to follow the releases to test that :)

Thank you.

**Comment by rqcy** [comment]
It would be very useful! Thanks for the great app!
