### ISSUE TITLE
Sounds volume settings

### ISSUE THREAD

**Issue by moshpirit** [tslocum/MeditationAssistant#4]
I'd like to have a sound volume settings for starting/intervals/end bells just when I'm meditating. Not sure how difficult is it.

**Comment by tslocum** [comment]
This has been on my mind for some time.  The way I am picturing it is, you enable the feature in settings, enter what volume level you want to use (1-10 for example), then when you meditate, all of the app's sounds follow this level.  Once you finish your session, your volume level is returned to what it was before meditating.  Does this line up with your idea?

**Comment by moshpirit** [comment]
That's perfect :) thank you!!

**Comment by tslocum** [comment]
This has been implemented in version 1.3.0
