### ISSUE TITLE
do not show the Sign in Medinet message

### ISSUE THREAD

**Issue by moshpirit** [tslocum/MeditationAssistant#6]
I'm not interested in using Medinet at all, so this welcome message is more annoying than useful so I would like to be able to hide it somehow.

Thanks beforehand.

It would be really useful too having a local data export/import without using Medinet at all.

**Comment by tslocum** [comment]
Thanks for the suggestions.  You can hide the MediNET button with the "Hide buttons" setting, and the local session export is in the TODO file.  I plan on implementing it in the near future.

**Comment by moshpirit** [comment]
But this only option hides the button, not the message

**Comment by tslocum** [comment]
You shouldn't be seeing the message unless you're trying to do something which requires signing in.  When you you usually see it?

**Comment by moshpirit** [comment]
When I open the app

**Comment by tslocum** [comment]
That's bizarre.  Could you please make sure the "Automatically connect" setting isn't checked?

**Comment by moshpirit** [comment]
Oh, OK! That was it, thank you :)
